name: '@nxworker workflow job setup'
description: 'Sets up the workflow job environment.'

env:
  NODE_OPTIONS: --max_old_space_size=4096
  PNPM_STORE_DIRECTORY: ~/.pnpm-store

inputs:
  node-version:
    description: 'Node.js version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - run: npm install --global pnpm
    - run: pnpm config set store-dir $PNPM_STORE_DIRECTORY
    - name: Cache PNPM store
      uses: actions/cache@v2
      with:
        path: ${{ env.PNPM_STORE_DIRECTORY }}
        key:
          ${{ runner.os }}-pnpm-${{ hashFiles('${{ github.action_path
          }}/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - run:
        pnpm install --reporter silent --frozen-lockfile false
        --verify-store-integrity false
    - run: pnpm store prune
