module.exports = {
  projects: [
    '<rootDir>/e2e/angular-e2e',
    '<rootDir>/e2e/examples/angular/nrwl-airlines/booking/desktop-app',
    '<rootDir>/e2e/examples/angular/nrwl-airlines/booking/mobile-app',
    '<rootDir>/e2e/examples/angular/nrwl-airlines/check-in/desktop-app',
    '<rootDir>/e2e/examples/angular/nrwl-airlines/check-in/mobile-app',
    '<rootDir>/packages/angular',
    '<rootDir>/packages/examples/angular/nrwl-airlines/booking/data-access',
    '<rootDir>/packages/examples/angular/nrwl-airlines/booking/feature-flight-search',
    '<rootDir>/packages/examples/angular/nrwl-airlines/booking/feature-passenger-info',
    '<rootDir>/packages/examples/angular/nrwl-airlines/booking/root/feature-shell',
    '<rootDir>/packages/examples/angular/nrwl-airlines/check-in/data-access',
    '<rootDir>/packages/examples/angular/nrwl-airlines/check-in/root/feature-shell',
    '<rootDir>/packages/examples/angular/nrwl-airlines/seatmap/data-access',
    '<rootDir>/packages/examples/angular/nrwl-airlines/seatmap/feature-seat-listing',
    '<rootDir>/packages/examples/angular/nrwl-airlines/shared/root/data-access',
    '<rootDir>/packages/examples/angular/nrwl-airlines/shared/ui-buttons',
    '<rootDir>/packages/examples/angular/nrwl-airlines/shared/util-formatting',
    '<rootDir>/packages/internal/e2e-util',
    '<rootDir>/packages/internal/test-util',
    '<rootDir>/tools',
  ],
};
