# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: '@nxworker/angular CI pipeline'

env:
  NODE_OPTIONS: --max_old_space_size=4096

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        angular-version: [11.0.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Variable-PNPM cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm cache dir)"
      - name: Cache PNPM cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key:
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{
            matrix.angular-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-pnpm-
      - run: pnpm install

      - run: pnpm lint

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        angular-version: [11.0.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Angular version ${{ matrix.angular-version }}
        uses: ngworker/angular-versions-action@v2
        with:
          angular_version: ${{ matrix.angular-version }}

      - name: Variable-PNPM cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm cache dir)"
      - name: Cache PNPM cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key:
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{
            matrix.angular-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-pnpm-
      - run: pnpm install

      - run: pnpm build:lib
      - uses: actions/upload-artifact@v2
        with:
          name: lumberjack-package
          path: dist/ngworker/lumberjack
          if-no-files-found: error

  lib:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        angular-version: [9.0.x, 9.1.x, 10.0.x, 10.1.x, 10.2.x, 11.0.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Angular version ${{ matrix.angular-version }}
        uses: ngworker/angular-versions-action@v2
        with:
          angular_version: ${{ matrix.angular-version }}

      - name: Variable-PNPM cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm cache dir)"
      - name: Cache PNPM cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key:
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{
            matrix.angular-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-pnpm-
      - run: pnpm install

      - run: pnpm test:internal:ci
      - run: pnpm test:lib:ci

  app:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        angular-version: [9.0.x, 9.1.x, 10.0.x, 10.1.x, 10.2.x, 11.0.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Angular version ${{ matrix.angular-version }}
        uses: ngworker/angular-versions-action@v2
        with:
          angular_version: ${{ matrix.angular-version }}

      - name: Variable-PNPM cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm cache dir)"
      - name: Cache PNPM cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key:
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{
            matrix.angular-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-pnpm-
      - run: pnpm install

      - run: pnpm delete-path-alias -- @ngworker/lumberjack
      - run: pnpm delete-path-alias -- @ngworker/lumberjack/*-driver
      - uses: actions/download-artifact@v2
        with:
          name: lumberjack-package
          path: node_modules/@ngworker/lumberjack
      - run: npx ngcc || true

      - run: pnpm test:ci
      - run: pnpm build

  e2e:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [12.x]
        angular-version: [9.0.x, 9.1.x, 10.0.x, 10.1.x, 10.2.x, 11.0.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Angular version ${{ matrix.angular-version }}
        uses: ngworker/angular-versions-action@v2
        with:
          angular_version: ${{ matrix.angular-version }}

      - name: Variable-PNPM cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm cache dir)"
      - name: Cache PNPM cache directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key:
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{
            matrix.angular-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-pnpm-
      - run: pnpm install

      - run: pnpm delete-path-alias -- @ngworker/lumberjack
      - run: pnpm delete-path-alias -- @ngworker/lumberjack/*-driver
      - uses: actions/download-artifact@v2
        with:
          name: lumberjack-package
          path: node_modules/@ngworker/lumberjack
      - run: npx ngcc || true

      - name: Update Chrome
        run: |
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
          google-chrome --version
      - run: pnpm e2e
